WeaponAccountingProject/Controllers/FileReaderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text;
using System.Data;
using WeaponAccountingProject.Data;
using WeaponAccountingProject.Models;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using System.Security.AccessControl;
using Microsoft.AspNetCore.Mvc.Rendering;
using WeaponAccountingProject.Interfaces;

namespace WeaponAccountingProject.Controllers
{
    public class FileReaderController : Controller
    {
        private List<List<String>> _fileData;
        private readonly IWeaponRepository _weaponRepository;
        public FileReaderController(IWeaponRepository weaponRepository)
        {
            _weaponRepository = weaponRepository;
        }
        public IActionResult Index()
        {
            ViewData["Locations"] = new SelectList(_weaponRepository.GetAllLocations(), "LocationId", "Name");
            //ViewBag.Data = _fileData;
            return View();
        }

        [HttpPost]
        public IActionResult Index(IFormFile file)
        {
            var Data = new List<List<string>> { };
            if (file == null || file.Length == 0)
            {
                return Content("File not selected");
            }
            using (var reader = new StreamReader(file.OpenReadStream(), Encoding.UTF8))
            {
                while (!reader.EndOfStream)
                {
                    var line = reader.ReadLine();
                    var lineWithDelimitor = replaceComaWithDotComa(line);
                    var values = lineWithDelimitor.Split(';').ToList();

                    Data.Add(values);
                }
                _fileData = Data;
                ViewBag.Data = Data;

                ViewData["Locations"] = new SelectList(_weaponRepository.GetAllLocations(), "LocationId", "Name");
                return View();
            }
        }

        private string replaceComaWithDotComa(string fileString)
        {
            string pattern = @"(,|\r?\n|`)([^`"",\r\n]+|""(?:[^""]|"")*"")?";
            string result = "";
            var regex = new Regex(pattern, RegexOptions.Compiled);
            MatchCollection matches = regex.Matches(fileString);

            foreach (Match match in matches)
            {
                if (match.Groups[1].Value == ",")
                {
                    // Add a tab character and the second group value (if exists)
                    result += ";" + (match.Groups[2].Success ? match.Groups[2].Value : "");
                }
                else
                {
                    // Add the entire match to the result
                    result += match.Value;
                }
            }

            return result;
        }
    }
}

WeaponAccountingProject/Controllers/WeaponController.cs
using Microsoft.AspNetCore.Mvc;
using WeaponAccountingProject.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using WeaponAccountingProject.Data;
using WeaponAccountingProject.Interfaces;
using WeaponAccountingProject.Models;
using Microsoft.EntityFrameworkCore;
using static WeaponAccountingProject.Repository.WeaponRepository;

namespace WeaponAccountingProject.Controllers
{
    public class WeaponController : Controller
    {
        private readonly IWeaponRepository _weaponRepository;
        public WeaponController(IWeaponRepository weaponRepository)
        {
            _weaponRepository = weaponRepository;
        }

        public IActionResult Index(WeaponSortField sortField = WeaponSortField.Name)
        {
            var weapons = _weaponRepository.SortAllWeapons(sortField); //SortAllWeapons();

            //var result = weapons.GroupBy(w => w.Name, w => w.WeaponId, 
            //                            (key, w) => new { Names = key, WeaponCount = w.Count()})
            //                            .OrderByDescending(w => w.WeaponCount).FirstOrDefault();

            return View(weapons);
        }

        [HttpGet]
        public Weapon GetWeapon(int id)
        {
            return _weaponRepository.GetWeapon(id);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createWeaponViewModel = new CreateWeaponViewModel();
            ViewData["Locations"] = new SelectList(_weaponRepository.GetAllLocations(), "LocationId", "Name");

            return View(createWeaponViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWeaponViewModel createWeaponVM)
        {
            if (ModelState.IsValid)
            {
                var weapon = new Weapon
                {
                    Name = createWeaponVM.Name,
                    RecordNumber = createWeaponVM.RecordNumber,
                    Year = createWeaponVM.Year,
                    LocationId = createWeaponVM.LocationId,
                    Value = createWeaponVM.Value
                };
                _weaponRepository.CreateWeapon(weapon);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var weapon = await _weaponRepository.GetWeaponAsync(id);
            if(weapon == null) return View("Error");

            //ViewData["Locations"] = new SelectList(_weaponRepository.GetAllLocations(), "LocationId", "Name");
            ViewData["Locations"] = new SelectList(await _weaponRepository.GetAllLocationsAsync(), "LocationId", "Name");

            var editWeaponViewModel = new EditWeaponViewModel
            {
                WeaponId = weapon.WeaponId,
                Name = weapon.Name,
                RecordNumber = weapon.RecordNumber,
                Year = weapon.Year,
                LocationId = weapon.LocationId,
                Value = weapon.Value
            };
            return View(editWeaponViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditWeaponViewModel editWeaponVM)
        {
            if (ModelState.IsValid)
            {
                var weapon = new Weapon
                {
                    WeaponId = editWeaponVM.WeaponId,
                    Name = editWeaponVM.Name,
                    RecordNumber = editWeaponVM.RecordNumber,
                    Year = editWeaponVM.Year,
                    LocationId = editWeaponVM.LocationId,
                    Value = editWeaponVM.Value
                };
                _weaponRepository.UpdateWeapon(weapon);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Failed to edit weapon");
            return RedirectToAction("Edit", editWeaponVM);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            _weaponRepository.DeleteWeapon(GetWeapon(id));

            return RedirectToAction("Index");
        }
    }
}

WeaponAccountingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeaponAccountingProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeaponAccountingProject.styles.css" asp-append-version="true" />
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeaponAccountingProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weapon" asp-action="Index">Weapons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileReader" asp-action="Index">File reader</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WeaponAccountingProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>